# Site settings
title: Waves.js
email: waves@ircam.fr
# description: > # this means to ignore newlines until "baseurl:"
  # Write an awesome description for your new site here. You can edit this
  # line in _config.yml. It will appear in your document head meta (for
  # Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "waves.github.io" # the base hostname & protocol for your site

github: "https://github.com/wavesjs"
download: "https://github.com/wavesjs/waves/archive/master.zip"
wavesUmd: ""
# use raw git for the moment, when in production update url to cdn rawgit
# same for jsfiddle examples

revision: 2.0


# Build settings
markdown: kramdown

collections:
 - docs